version: '3.9'

services:

  db:
    image: docker.io/library/postgres:13
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: dev
      POSTGRES_DB: postgres

  adminer:
    image: docker.io/library/adminer:latest
    restart: always
    ports:
      - 8080:8080
